package fedora

import (
	"context"
	_ "embed"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	imagecontract "github.com/ooaklee/lexr.sh/internal/image"
	"github.com/ooaklee/lexr.sh/internal/image/companion"
	"github.com/ooaklee/lexr.sh/internal/platform"
)

// fedoraGettingStartedTemplate is available through Files even without desktop icons.
//
//go:embed LEXR_GETTING_STARTED.txt
var fedoraGettingStartedTemplate string

// fedoraGettingStarted derives media discovery from the accepted source policy.
var fedoraGettingStarted = strings.ReplaceAll(fedoraGettingStartedTemplate, "@FEDORA_VOLUME_ID@", SourceVolumeID)

// fedoraRetainedMedia is inside the base image copied by Anaconda, outside its
// excluded /run live-medium mount. Its manifest remains the one ISO inventory.
const fedoraRetainedMedia = "usr/share/lexr/fedora-media"

// installFedoraUserSupport stages the guide and exact companion before SELinux
// relabelling and EROFS creation. It never changes Fedora's user creation hooks.
func installFedoraUserSupport(ctx context.Context, docker *platform.Docker, image, workspace, volume string, manifest imagecontract.Manifest) error {
	source := filepath.Join(workspace, filepath.FromSlash(companion.ISOFilesystemRoot))
	if err := companion.ValidateDirectory(manifest.CompanionBundle, source); err != nil {
		return fmt.Errorf("validate companion before Fedora retention: %w", err)
	}
	if err := writeFedoraUserSupportExpectations(workspace, manifest); err != nil {
		return err
	}
	included := "absent"
	if manifest.CompanionBundle.Included {
		included = "included"
	}
	if err := docker.RunInWorkspaceVolume(ctx, image, workspace, volume,
		"bash", "-ceu", installFedoraUserSupportScript, "lexr-retain-fedora-support", included); err != nil {
		return fmt.Errorf("stage Fedora live and installed user support: %w", err)
	}
	// Recheck the source as well as the copied directory, so a changed input
	// cannot silently become a different installed companion.
	if err := companion.ValidateDirectory(manifest.CompanionBundle, source); err != nil {
		return fmt.Errorf("revalidate Fedora companion source: %w", err)
	}
	return validateFedoraUserSupport(ctx, docker, image, workspace, volume, manifest)
}

// installFedoraUserSupportScript accepts only new adapter-owned destinations.
// Parent links and conflicting skeleton files fail before any copy occurs.
const installFedoraUserSupportScript = `root=/linux-work/rootfs
test ! -L "$root"
test -d "$root"
for relative in usr usr/share usr/share/lexr etc etc/skel etc/skel/Desktop; do
  test ! -L "$root/$relative"
  if test -e "$root/$relative"; then test -d "$root/$relative"; fi
done
media="$root/usr/share/lexr/fedora-media"
guide="$root/etc/skel/Desktop/LEXR_GETTING_STARTED.txt"
test ! -e "$media"
test ! -L "$media"
test ! -e "$guide"
test ! -L "$guide"
install -d -m 0755 "$media/sp11" "$root/etc/skel/Desktop"
install -m 0644 /work/fedora-getting-started.txt "$media/LEXR_GETTING_STARTED.txt"
install -m 0644 /work/fedora-getting-started.txt "$guide"
install -m 0644 /work/fedora-retained-manifest.json "$media/sp11/lexr-manifest.json"
if test "$1" = included; then
  cp -R -P --preserve=mode /work/sp11/companion "$media/sp11/companion"
fi
`

// writeFedoraUserSupportExpectations uses canonical generated bytes rather
// than executing any file from the source image during staging or inspection.
func writeFedoraUserSupportExpectations(workspace string, manifest imagecontract.Manifest) error {
	data, err := serialiseManifest(manifest)
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(workspace, "fedora-retained-manifest.json"), data, 0o644); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(workspace, "fedora-getting-started.txt"), []byte(fedoraGettingStarted), 0o644)
}

// validateFedoraUserSupport checks root-owned guides and manifest equality,
// then applies the existing closed companion-directory validator to a copy.
// No image-owned executable or shell fragment is run.
func validateFedoraUserSupport(ctx context.Context, docker *platform.Docker, image, workspace, volume string, manifest imagecontract.Manifest) (returnErr error) {
	if err := companion.ValidateRecord(manifest.CompanionBundle); err != nil {
		return err
	}
	if err := writeFedoraUserSupportExpectations(workspace, manifest); err != nil {
		return err
	}
	exported, err := os.MkdirTemp(workspace, ".fedora-retained-check-")
	if err != nil {
		return err
	}
	defer func() {
		if err := os.RemoveAll(exported); err != nil {
			returnErr = errors.Join(returnErr, fmt.Errorf("remove private Fedora companion export: %w", err))
		}
	}()
	included := "absent"
	if manifest.CompanionBundle.Included {
		included = "included"
	}
	if err := docker.RunInWorkspaceVolume(ctx, image, workspace, volume,
		"bash", "-ceu", validateFedoraUserSupportScript, "lexr-check-fedora-support", included, "/work/"+filepath.Base(exported)); err != nil {
		return fmt.Errorf("inspect retained Fedora user support: %w", err)
	}
	return companion.ValidateDirectory(manifest.CompanionBundle, filepath.Join(exported, "companion"))
}

// validateFedoraUserSupportScript inspects links before copying, preserves
// directory modes, and rejects extra support-root members or undeclared bundles.
const validateFedoraUserSupportScript = `export_root=$2
# The export root was created by the host user. Fix only this private copy,
# including failed copies, without following payload links or changing sources.
trap 'export_status=$?; chown -hR -P --reference="$export_root" "$export_root" || exit 1; exit "$export_status"' EXIT
root=/linux-work/rootfs
test ! -L "$root"
test -d "$root"
for relative in usr usr/share usr/share/lexr usr/share/lexr/fedora-media usr/share/lexr/fedora-media/sp11 etc etc/skel etc/skel/Desktop; do
  test ! -L "$root/$relative"
  test -d "$root/$relative"
done
media="$root/usr/share/lexr/fedora-media"
for relative in usr/share/lexr/fedora-media/LEXR_GETTING_STARTED.txt etc/skel/Desktop/LEXR_GETTING_STARTED.txt usr/share/lexr/fedora-media/sp11/lexr-manifest.json; do
  file="$root/$relative"
  test ! -L "$file"
  test -f "$file"
  test "$(stat -c '%a:%u:%g' "$file")" = 644:0:0
done
cmp /work/fedora-getting-started.txt "$media/LEXR_GETTING_STARTED.txt"
cmp /work/fedora-getting-started.txt "$root/etc/skel/Desktop/LEXR_GETTING_STARTED.txt"
cmp /work/fedora-retained-manifest.json "$media/sp11/lexr-manifest.json"
test "$(find "$media" -mindepth 1 -maxdepth 1 -printf '%f\n' | LC_ALL=C sort)" = "LEXR_GETTING_STARTED.txt
sp11"
if test "$1" = included; then
  test ! -L "$media/sp11/companion"
  test -d "$media/sp11/companion"
  # Ownership repair of the export can clear set-ID bits. Inspect the native
  # tree first so copying cannot hide unsafe original permissions or owners.
  cli="$media/sp11/companion/bin/linux-arm64/lexr"
  test "$(stat -c '%a:%u:%g' "$cli")" = 755:0:0
  test -z "$(find "$media/sp11/companion" \( ! -uid 0 -o ! -gid 0 \) -print)"
  test -z "$(find "$media/sp11/companion" -type d ! -perm 0755 -print)"
  test -z "$(find "$media/sp11/companion" -type f ! -path "$cli" ! -perm 0644 -print)"
  test "$(find "$media/sp11" -mindepth 1 -maxdepth 1 -printf '%f\n' | LC_ALL=C sort)" = "companion
lexr-manifest.json"
  cp -R -P --preserve=mode "$media/sp11/companion" "$2/companion"
else
  test ! -e "$media/sp11/companion"
  test ! -L "$media/sp11/companion"
  test "$(find "$media/sp11" -mindepth 1 -maxdepth 1 -printf '%f\n')" = lexr-manifest.json
fi
`

// validateFedoraUserSupportContexts checks the Fedora 44 policy types after
// EROFS relabelling/extraction. The live home is separately restored by livesys.
func validateFedoraUserSupportContexts(ctx context.Context, docker *platform.Docker, image, workspace, volume string, included bool) error {
	files := map[string]string{
		fedoraRetainedMedia + "/LEXR_GETTING_STARTED.txt": "system_u:object_r:usr_t:s0",
		"etc/skel/Desktop/LEXR_GETTING_STARTED.txt":       "system_u:object_r:etc_t:s0",
	}
	if included {
		files[fedoraRetainedMedia+"/sp11/companion/bin/linux-arm64/lexr"] = "system_u:object_r:bin_t:s0"
	}
	for path, expected := range files {
		output, err := docker.CaptureInWorkspaceVolume(ctx, image, workspace, volume,
			"getfattr", "--only-values", "-n", "security.selinux", "/linux-work/rootfs/"+path)
		if err != nil {
			return fmt.Errorf("inspect Fedora support SELinux context %s: %w", path, err)
		}
		if strings.TrimRight(string(output), "\x00\n") != expected {
			return fmt.Errorf("Fedora support SELinux context %s differs from %s", path, expected)
		}
	}
	return nil
}
