version: 2

project_name: lexr
dist: dist

gomod:
  dir: .

builds:
  - id: lexr
    dir: .
    main: ./cmd/lexr
    binary: lexr
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - >-
        -s -w
        -X github.com/ooaklee/lexr.sh/internal/version.Version={{ .Version }}
        -X github.com/ooaklee/lexr.sh/internal/version.Commit={{ .FullCommit }}
        -X github.com/ooaklee/lexr.sh/internal/version.Date={{ .Date }}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: release-binaries
    ids:
      - lexr
    formats:
      - binary
    name_template: >-
      {{ .ProjectName }}-v
      {{- .Version }}-
      {{- .Os }}-
      {{- .Arch }}

checksum:
  name_template: "{{ .ProjectName }}-v{{ .Version }}.sha256sums"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  draft: false
  make_latest: false
