package ubuntu

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/ooaklee/lexr.sh/internal/kernel"
	kernelinstall "github.com/ooaklee/lexr.sh/internal/kernel/install"
	"github.com/ooaklee/lexr.sh/internal/platform"
)

// installedGrubDefaultsName is the sole device-specific support file staged by
// the Ubuntu adapter rather than supplied by the generic Debian package.
const installedGrubDefaultsName = "99-surface-pro-11.cfg"

// retiredInstalledSupportPaths lists the adapter-generated lifecycle files
// which must not survive migration to package-owned boot support.
var retiredInstalledSupportPaths = []string{
	"etc/grub.d/09_lexr_sp11",
	"etc/kernel/postinst.d/05-lexr-sp11-dtb",
	"etc/kernel/postrm.d/05-lexr-sp11-dtb",
	"usr/local/sbin/lexr-refresh-sp11-boot",
	"usr/lib/lexr/sp11/kernel-abi",
	"usr/lib/lexr/sp11/dtb/x1e80100-microsoft-denali-oled.dtb",
	"usr/lib/lexr/sp11/dtb/x1p64100-microsoft-denali.dtb",
}

// genericInstalledSupportPaths lists the package-owned files common to every
// external-required installed-system hand-off.
var genericInstalledSupportPaths = []string{
	"etc/kernel/postinst.d/05-lexr-kernel-boot",
	"etc/kernel/postrm.d/05-lexr-kernel-boot",
	"usr/libexec/lexr/kernel-boot-refresh",
	"usr/lib/lexr/kernel-build/abi",
	"usr/lib/lexr/kernel-build/version",
	"usr/lib/lexr/kernel-build/platforms",
}

// stageInstalledSupportFiles retains only the genuinely device-specific GRUB
// defaults. External DTB lifecycle files are supplied by the bundle's generic
// boot-support package and must never be generated by the Ubuntu adapter.
func stageInstalledSupportFiles(workspace string) error {
	directory := filepath.Join(workspace, "installed-support")
	if err := os.MkdirAll(directory, 0o755); err != nil {
		return fmt.Errorf("create installed-system support staging directory: %w", err)
	}
	if err := os.WriteFile(filepath.Join(directory, installedGrubDefaultsName), []byte(installedGrubDefaults()), 0o644); err != nil {
		return fmt.Errorf("stage installed GRUB defaults: %w", err)
	}
	return nil
}

// installKernelPackages registers the exact runtime packages and, only for an
// external-required bundle, its manifest-declared generic boot-support package.
// Kernel hooks are suppressed only while the image and modules are configured;
// the support package is installed after those directories are restored so its
// package-owned hooks remain consistent with dpkg's database.
func installKernelPackages(ctx context.Context, docker *platform.Docker, image, workspace, volume string, bundle kernel.Bundle) error {
	imagePackage, ok := bundle.Package(kernel.RoleImage)
	if !ok {
		return errorsForMissingKernelRole(kernel.RoleImage)
	}
	modulesPackage, ok := bundle.Package(kernel.RoleModules)
	if !ok {
		return errorsForMissingKernelRole(kernel.RoleModules)
	}
	supportArchive := ""
	if bundle.EffectiveDTBDelivery == kernel.DTBDeliveryExternalRequired {
		supportPackage, found := bundle.Package(kernel.RoleBootSupport)
		if !found {
			return errorsForMissingKernelRole(kernel.RoleBootSupport)
		}
		supportArchive = "/work/kernel/" + supportPackage.Name
	} else if _, found := bundle.Package(kernel.RoleBootSupport); found {
		return fmt.Errorf("embedded kernel bundle unexpectedly contains a %s package", kernel.RoleBootSupport)
	}

	const script = `root=/linux-work/rootfs
abi=$1
version=$2
modules_archive=$3
image_archive=$4
support_archive=$5
modules_package="linux-modules-$abi"
image_package="linux-image-$abi"
support_package=lexr-kernel-boot-support

verify_archive() {
	archive=$1
	expected_package=$2
	expected_architecture=$3
	actual_package=$(dpkg-deb --field "$archive" Package)
	actual_version=$(dpkg-deb --field "$archive" Version)
	actual_architecture=$(dpkg-deb --field "$archive" Architecture)
	[ "$actual_package" = "$expected_package" ] || {
		echo "kernel archive $archive declares package $actual_package, expected $expected_package" >&2
		exit 65
	}
	[ "$actual_version" = "$version" ] || {
		echo "kernel archive $archive declares version $actual_version, expected $version" >&2
		exit 65
	}
	[ "$actual_architecture" = "$expected_architecture" ] || {
		echo "kernel archive $archive declares architecture $actual_architecture, expected $expected_architecture" >&2
		exit 65
	}
}

verify_archive "$modules_archive" "$modules_package" arm64
verify_archive "$image_archive" "$image_package" arm64
if [ -n "$support_archive" ]; then
	verify_archive "$support_archive" "$support_package" all
fi

backup=/linux-work/dpkg-offline-backup
[ ! -e "$backup" ] || {
	echo "refusing to reuse an existing offline dpkg backup" >&2
	exit 73
}
mkdir -m 0700 "$backup"

restore_hook_directories() {
	for phase in preinst.d postinst.d; do
		if [ -e "$backup/$phase" ]; then
			rm -rf -- "$root/etc/kernel/$phase"
			mv "$backup/$phase" "$root/etc/kernel/$phase"
		elif [ -e "$backup/$phase.absent" ]; then
			rm -rf -- "$root/etc/kernel/$phase"
			rm -f -- "$backup/$phase.absent"
		fi
	done
}

restore_statoverride() {
	if [ -e "$backup/statoverride" ]; then
		rm -f -- "$root/var/lib/dpkg/statoverride"
		mv "$backup/statoverride" "$root/var/lib/dpkg/statoverride"
	elif [ -e "$backup/statoverride.absent" ]; then
		rm -f -- "$root/var/lib/dpkg/statoverride" "$backup/statoverride.absent"
	fi
}

restore_offline_state() {
	status=$?
	restore_hook_directories
	restore_statoverride
	rm -rf -- "$backup"
	trap - EXIT HUP INT TERM
	exit "$status"
}
trap restore_offline_state EXIT HUP INT TERM

for phase in preinst.d postinst.d; do
	if [ -e "$root/etc/kernel/$phase" ]; then
		mv "$root/etc/kernel/$phase" "$backup/$phase"
	else
		: > "$backup/$phase.absent"
	fi
	mkdir -p "$root/etc/kernel/$phase"
done

# The minimal layer's statoverride database names accounts supplied by upper
# Casper layers. Hide it only while the selected packages are installed, then
# restore the original bytes even when dpkg or an interrupt stops the build.
if [ -e "$root/var/lib/dpkg/statoverride" ]; then
	mv "$root/var/lib/dpkg/statoverride" "$backup/statoverride"
else
	: > "$backup/statoverride.absent"
fi
: > "$root/var/lib/dpkg/statoverride"

# Offline kernel hooks may expect mounted target devices or create a live
# initramfs. Register the runtime packages first, then restore the real hook
# directories before installing the package which owns Lexr's lifecycle hook.
dpkg --root="$root" --install "$modules_archive" "$image_archive"
restore_hook_directories
if [ -n "$support_archive" ]; then
	dpkg --root="$root" --install "$support_archive"
fi

chroot "$root" dpkg-query --show --showformat='${Package}\t${Version}\t${Architecture}\t${db:Status-Status}\n' \
	"$modules_package" "$image_package" > /linux-work/kernel-package-status
expected_modules=$(printf '%s\t%s\tarm64\tinstalled' "$modules_package" "$version")
expected_image=$(printf '%s\t%s\tarm64\tinstalled' "$image_package" "$version")
grep -Fx "$expected_modules" /linux-work/kernel-package-status >/dev/null
grep -Fx "$expected_image" /linux-work/kernel-package-status >/dev/null
if [ -n "$support_archive" ]; then
	chroot "$root" dpkg-query --show --showformat='${Package}\t${Version}\t${Architecture}\t${db:Status-Status}\n' \
		"$support_package" > /linux-work/boot-support-package-status
	expected_support=$(printf '%s\t%s\tall\tinstalled' "$support_package" "$version")
	grep -Fx "$expected_support" /linux-work/boot-support-package-status >/dev/null
fi

restore_statoverride
rm -rf -- "$backup"
trap - EXIT HUP INT TERM
`
	if err := docker.RunInWorkspaceVolume(ctx, image, workspace, volume,
		"bash", "-ceu", script, "lexr-install-kernel", bundle.ABI, bundle.Version,
		"/work/kernel/"+modulesPackage.Name, "/work/kernel/"+imagePackage.Name, supportArchive); err != nil {
		return fmt.Errorf("register custom kernel packages in remastered root: %w", err)
	}
	return nil
}

// errorsForMissingKernelRole returns a consistent error for an incomplete
// kernel bundle passed to the installed-system hand-off.
func errorsForMissingKernelRole(role kernel.PackageRole) error {
	return fmt.Errorf("kernel bundle has no %s package", role)
}

// installInstalledSystemSupport retains Surface command-line defaults, invokes
// the package-owned helper for every external profile, creates the non-Casper
// initramfs, and regenerates and verifies GRUB exactly once afterwards.
func installInstalledSystemSupport(ctx context.Context, docker *platform.Docker, image, workspace, volume string, bundle kernel.Bundle) error {
	profile, _, err := requiredExternalProfile(bundle)
	if err != nil {
		return err
	}
	const script = `root=/linux-work/rootfs
abi=$1
delivery=$2
shift 2
support=/work/installed-support

install -d -m 0755 "$root/etc/default/grub.d"
install -m 0644 "$support/99-surface-pro-11.cfg" "$root/etc/default/grub.d/99-surface-pro-11.cfg"

# Fresh images must not carry the retired adapter-generated lifecycle beside
# the generic package-owned implementation.
rm -f -- \
	"$root/etc/grub.d/09_lexr_sp11" \
	"$root/etc/kernel/postinst.d/05-lexr-sp11-dtb" \
	"$root/etc/kernel/postrm.d/05-lexr-sp11-dtb" \
	"$root/usr/local/sbin/lexr-refresh-sp11-boot" \
	"$root/usr/lib/lexr/sp11/kernel-abi" \
	"$root/usr/lib/lexr/sp11/dtb/x1e80100-microsoft-denali-oled.dtb" \
	"$root/usr/lib/lexr/sp11/dtb/x1p64100-microsoft-denali.dtb"
rmdir -- "$root/usr/lib/lexr/sp11/dtb" "$root/usr/lib/lexr/sp11" 2>/dev/null || true

case "$delivery" in
	external-required)
		[ -x "$root/usr/libexec/lexr/kernel-boot-refresh" ] || {
			echo "external-required image has no package-owned boot refresh helper" >&2
			exit 66
		}
		[ "$#" -gt 0 ] || {
			echo "external-required image has no declared platform profile" >&2
			exit 66
		}
		for profile in "$@"; do
			chroot "$root" /usr/libexec/lexr/kernel-boot-refresh refresh \
				--root / --abi "$abi" --image "/boot/vmlinuz-$abi" \
				--platform "$profile" --defer-grub
		done
		;;
	embedded)
		[ "$#" -eq 0 ] || {
			echo "embedded image unexpectedly received external platform profiles" >&2
			exit 65
		}
		[ ! -e "$root/usr/libexec/lexr/kernel-boot-refresh" ] || {
			echo "embedded image unexpectedly contains external boot support" >&2
			exit 65
		}
		;;
	*)
		echo "unsupported effective DTB delivery $delivery" >&2
		exit 65
		;;
esac

test -x "$root/usr/sbin/update-initramfs"
rm -f -- "$root/boot/initrd.img-$abi"
chroot "$root" update-initramfs -c -k "$abi"
test -s "$root/boot/initrd.img-$abi"
test -x "$root/usr/sbin/update-grub"
chroot "$root" update-grub
test -s "$root/boot/grub/grub.cfg"
chroot "$root" grub-script-check /boot/grub/grub.cfg
`
	arguments := []string{
		"bash", "-ceu", script, "lexr-installed-support", bundle.ABI, string(bundle.EffectiveDTBDelivery),
	}
	if profile != "" {
		arguments = append(arguments, profile)
	}
	if err := docker.RunInWorkspaceVolume(ctx, image, workspace, volume, arguments...); err != nil {
		return fmt.Errorf("install exact-ABI kernel, DTB, GRUB, and initramfs support: %w", err)
	}
	return nil
}

// installedGrubDefaults returns the installed operating system's Surface
// command line without the live-media-only USB safety blacklist.
func installedGrubDefaults() string {
	return `# Surface Pro 11 platform arguments for installed kernels.
GRUB_CMDLINE_LINUX_DEFAULT="${GRUB_CMDLINE_LINUX_DEFAULT} clk_ignore_unused pd_ignore_unused arm64.nopauth systemd.tpm2_wait=0"
GRUB_TIMEOUT_STYLE=menu
GRUB_TIMEOUT=15
`
}

// requiredExternalProfile returns the one package-registry profile selected
// for a raw image. A multi-profile installed image must use embedded delivery.
func requiredExternalProfile(bundle kernel.Bundle) (string, kernel.DeviceTree, error) {
	if bundle.EffectiveDTBDelivery == kernel.DTBDeliveryEmbedded {
		return "", kernel.DeviceTree{}, nil
	}
	if bundle.EffectiveDTBDelivery != kernel.DTBDeliveryExternalRequired {
		return "", kernel.DeviceTree{}, fmt.Errorf("unsupported effective DTB delivery %q", bundle.EffectiveDTBDelivery)
	}
	var selected kernel.DeviceTree
	count := 0
	for _, tree := range bundle.DeviceTrees {
		if tree.Required {
			selected = tree
			count++
		}
	}
	if count != 1 {
		return "", kernel.DeviceTree{}, fmt.Errorf("external-required installed image requires exactly one platform profile; found %d (use embedded delivery for multi-profile media)", count)
	}
	return selected.Device, selected, nil
}

// installedPackageExpectation is one exact dpkg record required in the
// deployable root.
type installedPackageExpectation struct {
	name         string
	version      string
	architecture string
}

// installedPackageExpectations returns the package database records required
// by this bundle's effective delivery contract.
func installedPackageExpectations(bundle kernel.Bundle) []installedPackageExpectation {
	expected := []installedPackageExpectation{
		{name: "linux-modules-" + bundle.ABI, version: bundle.Version, architecture: "arm64"},
		{name: "linux-image-" + bundle.ABI, version: bundle.Version, architecture: "arm64"},
	}
	if bundle.EffectiveDTBDelivery == kernel.DTBDeliveryExternalRequired {
		expected = append(expected, installedPackageExpectation{
			name: "lexr-kernel-boot-support", version: bundle.Version, architecture: "all",
		})
	}
	return expected
}

// installedSupportPaths returns the bundle-bound live-root paths which
// validation extracts before assessing the installed-system hand-off.
func installedSupportPaths(bundle kernel.Bundle) ([]string, error) {
	paths := []string{
		"boot/vmlinuz-" + bundle.ABI,
		"boot/initrd.img-" + bundle.ABI,
		"boot/grub/grub.cfg",
		"etc/default/grub.d/" + installedGrubDefaultsName,
		"var/lib/dpkg/status",
	}
	for _, expected := range installedPackageExpectations(bundle) {
		paths = append(paths, "var/lib/dpkg/info/"+expected.name+".list")
	}
	if bundle.EffectiveDTBDelivery == kernel.DTBDeliveryEmbedded {
		return paths, nil
	}
	profile, tree, err := requiredExternalProfile(bundle)
	if err != nil {
		return nil, err
	}
	paths = append(paths, genericInstalledSupportPaths...)
	relative, ok := tree.FirmwareRelativePath(bundle.ABI)
	if !ok {
		return nil, fmt.Errorf("device tree %s is outside the exact-ABI firmware directory", tree.Device)
	}
	paths = append(paths, "boot/dtbs/"+bundle.ABI+"/"+relative, "boot/dtb-"+bundle.ABI)
	for _, name := range []string{"title", "dtb-path", "dtb-sha256", "machine-identities", "compatibles"} {
		paths = append(paths,
			"usr/lib/lexr/kernel-platforms/"+profile+"/"+name,
			"var/lib/lexr/kernel-boot/"+bundle.ABI+"/"+profile+"/"+name,
		)
	}
	return paths, nil
}

// installedPackageStatus reports whether one exact package stanza is marked as
// installed with the expected version and architecture.
func installedPackageStatus(status, packageName, version, architecture string) bool {
	for _, paragraph := range strings.Split(strings.ReplaceAll(status, "\r\n", "\n"), "\n\n") {
		fields := make(map[string]string)
		for _, line := range strings.Split(paragraph, "\n") {
			key, value, ok := strings.Cut(line, ":")
			if ok {
				fields[key] = strings.TrimSpace(value)
			}
		}
		if fields["Package"] == packageName && fields["Version"] == version &&
			fields["Architecture"] == architecture && fields["Status"] == "install ok installed" {
			return true
		}
	}
	return false
}

// installedPackagePresent reports whether any status paragraph declares the
// exact package name, regardless of configuration state.
func installedPackagePresent(status, packageName string) bool {
	for _, paragraph := range strings.Split(strings.ReplaceAll(status, "\r\n", "\n"), "\n\n") {
		for _, line := range strings.Split(paragraph, "\n") {
			if line == "Package: "+packageName {
				return true
			}
		}
	}
	return false
}

// squashFSListingContainsPath matches one exact member in unsquashfs -ll
// output without accepting a basename prefix or suffix.
func squashFSListingContainsPath(listing, wanted string) bool {
	wanted = strings.TrimPrefix(filepath.ToSlash(wanted), "/")
	for _, line := range strings.Split(listing, "\n") {
		fields := strings.Fields(line)
		if len(fields) == 0 {
			continue
		}
		candidate := strings.TrimPrefix(filepath.ToSlash(fields[len(fields)-1]), "squashfs-root/")
		if candidate == wanted {
			return true
		}
	}
	return false
}

// validateInstalledGRUBEntries proves every entry which boots the exact target
// image also carries the delivery mode's initramfs and DTB contract. This
// rejects any stock 10_linux entry which omits the selected /dtb-<abi> copy.
func validateInstalledGRUBEntries(ctx context.Context, root string, bundle kernel.Bundle, entries []kernelinstall.GRUBEntry) error {
	externalNormal := 0
	externalRecovery := 0
	if bundle.EffectiveDTBDelivery == kernel.DTBDeliveryExternalRequired {
		if _, _, err := requiredExternalProfile(bundle); err != nil {
			return err
		}
	}

	matching := 0
	abiLabelledNormal := 0
	embeddedNormal := 0
	embeddedRecovery := 0
	for _, entry := range entries {
		if kernelinstall.GRUBEntryHasUnsafeBootArtifacts(entry) {
			return fmt.Errorf("target GRUB entry %q contains an unsafe kernel or initramfs path", entry.Title)
		}
	}
	for _, entry := range entries {
		if !grubTokensName(entry.Linux, "vmlinuz-"+bundle.ABI) {
			continue
		}
		matching++
		if err := kernelinstall.VerifyGRUBEntryABIArtifacts(ctx, root, entry, bundle.ABI); err != nil {
			return fmt.Errorf("target GRUB entry %q: %w", entry.Title, err)
		}
		if !entry.Recovery && strings.Contains(entry.Title, bundle.ABI) {
			abiLabelledNormal++
		}
		if len(entry.UnsafeCommands) != 0 {
			return fmt.Errorf("target GRUB entry %q contains unsafe boot paths", entry.Title)
		}
		switch bundle.EffectiveDTBDelivery {
		case kernel.DTBDeliveryExternalRequired:
			if len(entry.DeviceTrees) != 1 {
				return fmt.Errorf("external-required target GRUB entry %q has %d device-tree directives; expected one", entry.Title, len(entry.DeviceTrees))
			}
			if !grubTokensExactPath(entry.DeviceTrees, "/dtb-"+bundle.ABI) {
				return fmt.Errorf("target GRUB entry %q does not bind the selected /dtb-%s", entry.Title, bundle.ABI)
			}
			if entry.Recovery {
				externalRecovery++
			} else {
				externalNormal++
			}
		case kernel.DTBDeliveryEmbedded:
			if len(entry.DeviceTrees) != 0 {
				return fmt.Errorf("embedded target GRUB entry %q has an external device-tree directive", entry.Title)
			}
			if entry.Recovery {
				embeddedRecovery++
			} else {
				embeddedNormal++
			}
		default:
			return fmt.Errorf("unsupported effective DTB delivery %q", bundle.EffectiveDTBDelivery)
		}
	}
	if matching == 0 {
		return fmt.Errorf("installed GRUB has no entry for target ABI %s", bundle.ABI)
	}
	if abiLabelledNormal != 1 {
		return fmt.Errorf("target ABI requires exactly one ABI-labelled non-recovery GRUB entry; found %d", abiLabelledNormal)
	}
	if bundle.EffectiveDTBDelivery == kernel.DTBDeliveryEmbedded {
		if embeddedNormal == 0 || embeddedRecovery == 0 {
			return fmt.Errorf("embedded target ABI requires normal and recovery GRUB entries")
		}
		return nil
	}
	if externalNormal == 0 || externalRecovery == 0 {
		return fmt.Errorf("external-required target ABI lacks a selected-DTB normal or recovery GRUB entry")
	}
	return nil
}

// grubTokensName reports whether one parsed command list names the exact
// basename without trusting the containing path.
func grubTokensName(tokens []kernelinstall.GRUBPathToken, basename string) bool {
	for _, token := range tokens {
		if filepath.Base(filepath.ToSlash(token.Path)) == basename {
			return true
		}
	}
	return false
}

// grubTokensExactPath reports whether one parsed command names the expected
// absolute GRUB path rather than a same-basename file in another directory.
func grubTokensExactPath(tokens []kernelinstall.GRUBPathToken, expected string) bool {
	expected = filepath.ToSlash(filepath.Clean(expected))
	for _, token := range tokens {
		if filepath.ToSlash(filepath.Clean(token.Path)) == expected {
			return true
		}
	}
	return false
}
