package ubuntu

import (
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/ooaklee/lexr.sh/internal/kernel"
	"github.com/ooaklee/lexr.sh/internal/platform"
)

// installedGrubDefaultsName is the sole device-specific support file staged by
// the Ubuntu adapter rather than supplied by the generic Debian package.
const installedGrubDefaultsName = "99-surface-pro-11.cfg"

// maximumInstalledGRUBGeneratorBytes bounds the stock generator inspected from
// an untrusted source image before the installer has a real target disk.
const maximumInstalledGRUBGeneratorBytes int64 = 256 << 10

// retiredInstalledSupportPaths lists the adapter-generated lifecycle files
// which must not survive migration to package-owned boot support.
var retiredInstalledSupportPaths = []string{
	"etc/grub.d/09_lexr_sp11",
	"etc/kernel/postinst.d/05-lexr-sp11-dtb",
	"etc/kernel/postrm.d/05-lexr-sp11-dtb",
	"usr/local/sbin/lexr-refresh-sp11-boot",
	"usr/lib/lexr/sp11/kernel-abi",
	"usr/lib/lexr/sp11/dtb/x1e80100-microsoft-denali-oled.dtb",
	"usr/lib/lexr/sp11/dtb/x1p64100-microsoft-denali.dtb",
}

// genericInstalledSupportPaths lists the package-owned files common to every
// external-required installed-system hand-off.
var genericInstalledSupportPaths = []string{
	"etc/kernel/postinst.d/05-lexr-kernel-boot",
	"etc/kernel/postrm.d/05-lexr-kernel-boot",
	"usr/libexec/lexr/kernel-boot-refresh",
	"usr/lib/lexr/kernel-build/abi",
	"usr/lib/lexr/kernel-build/version",
	"usr/lib/lexr/kernel-build/platforms",
}

// stageInstalledSupportFiles retains only the genuinely device-specific GRUB
// defaults. External DTB lifecycle files are supplied by the bundle's generic
// boot-support package and must never be generated by the Ubuntu adapter.
func stageInstalledSupportFiles(workspace string) error {
	directory := filepath.Join(workspace, "installed-support")
	if err := os.MkdirAll(directory, 0o755); err != nil {
		return fmt.Errorf("create installed-system support staging directory: %w", err)
	}
	if err := os.WriteFile(filepath.Join(directory, installedGrubDefaultsName), []byte(installedGrubDefaults()), 0o644); err != nil {
		return fmt.Errorf("stage installed GRUB defaults: %w", err)
	}
	return nil
}

// installKernelPackages registers the exact runtime packages and, only for an
// external-required bundle, its manifest-declared generic boot-support package.
// Kernel hooks are suppressed only while the image and modules are configured;
// the support package is installed after those directories are restored so its
// package-owned hooks remain consistent with dpkg's database.
func installKernelPackages(ctx context.Context, docker *platform.Docker, image, workspace, volume string, bundle kernel.Bundle) error {
	imagePackage, ok := bundle.Package(kernel.RoleImage)
	if !ok {
		return errorsForMissingKernelRole(kernel.RoleImage)
	}
	modulesPackage, ok := bundle.Package(kernel.RoleModules)
	if !ok {
		return errorsForMissingKernelRole(kernel.RoleModules)
	}
	supportArchive := ""
	if bundle.EffectiveDTBDelivery == kernel.DTBDeliveryExternalRequired {
		supportPackage, found := bundle.Package(kernel.RoleBootSupport)
		if !found {
			return errorsForMissingKernelRole(kernel.RoleBootSupport)
		}
		supportArchive = "/work/kernel/" + supportPackage.Name
	} else if _, found := bundle.Package(kernel.RoleBootSupport); found {
		return fmt.Errorf("embedded kernel bundle unexpectedly contains a %s package", kernel.RoleBootSupport)
	}

	const script = `root=/linux-work/rootfs
abi=$1
version=$2
modules_archive=$3
image_archive=$4
support_archive=$5
modules_package="linux-modules-$abi"
image_package="linux-image-$abi"
support_package=lexr-kernel-boot-support

verify_archive() {
	archive=$1
	expected_package=$2
	expected_architecture=$3
	actual_package=$(dpkg-deb --field "$archive" Package)
	actual_version=$(dpkg-deb --field "$archive" Version)
	actual_architecture=$(dpkg-deb --field "$archive" Architecture)
	[ "$actual_package" = "$expected_package" ] || {
		echo "kernel archive $archive declares package $actual_package, expected $expected_package" >&2
		exit 65
	}
	[ "$actual_version" = "$version" ] || {
		echo "kernel archive $archive declares version $actual_version, expected $version" >&2
		exit 65
	}
	[ "$actual_architecture" = "$expected_architecture" ] || {
		echo "kernel archive $archive declares architecture $actual_architecture, expected $expected_architecture" >&2
		exit 65
	}
}

verify_archive "$modules_archive" "$modules_package" arm64
verify_archive "$image_archive" "$image_package" arm64
if [ -n "$support_archive" ]; then
	verify_archive "$support_archive" "$support_package" all
fi

backup=/linux-work/dpkg-offline-backup
[ ! -e "$backup" ] || {
	echo "refusing to reuse an existing offline dpkg backup" >&2
	exit 73
}
mkdir -m 0700 "$backup"

restore_hook_directories() {
	for phase in preinst.d postinst.d; do
		if [ -e "$backup/$phase" ]; then
			rm -rf -- "$root/etc/kernel/$phase"
			mv "$backup/$phase" "$root/etc/kernel/$phase"
		elif [ -e "$backup/$phase.absent" ]; then
			rm -rf -- "$root/etc/kernel/$phase"
			rm -f -- "$backup/$phase.absent"
		fi
	done
}

restore_statoverride() {
	if [ -e "$backup/statoverride" ]; then
		rm -f -- "$root/var/lib/dpkg/statoverride"
		mv "$backup/statoverride" "$root/var/lib/dpkg/statoverride"
	elif [ -e "$backup/statoverride.absent" ]; then
		rm -f -- "$root/var/lib/dpkg/statoverride" "$backup/statoverride.absent"
	fi
}

restore_offline_state() {
	status=$?
	restore_hook_directories
	restore_statoverride
	rm -rf -- "$backup"
	trap - EXIT HUP INT TERM
	exit "$status"
}
trap restore_offline_state EXIT HUP INT TERM

for phase in preinst.d postinst.d; do
	if [ -e "$root/etc/kernel/$phase" ]; then
		mv "$root/etc/kernel/$phase" "$backup/$phase"
	else
		: > "$backup/$phase.absent"
	fi
	mkdir -p "$root/etc/kernel/$phase"
done

# The minimal layer's statoverride database names accounts supplied by upper
# Casper layers. Hide it only while the selected packages are installed, then
# restore the original bytes even when dpkg or an interrupt stops the build.
if [ -e "$root/var/lib/dpkg/statoverride" ]; then
	mv "$root/var/lib/dpkg/statoverride" "$backup/statoverride"
else
	: > "$backup/statoverride.absent"
fi
: > "$root/var/lib/dpkg/statoverride"

# Offline kernel hooks may expect mounted target devices or create a live
# initramfs. Register the runtime packages first, then restore the real hook
# directories before installing the package which owns Lexr's lifecycle hook.
dpkg --root="$root" --install "$modules_archive" "$image_archive"
restore_hook_directories
if [ -n "$support_archive" ]; then
	dpkg --root="$root" --install "$support_archive"
fi

chroot "$root" dpkg-query --show --showformat='${Package}\t${Version}\t${Architecture}\t${db:Status-Status}\n' \
	"$modules_package" "$image_package" > /linux-work/kernel-package-status
expected_modules=$(printf '%s\t%s\tarm64\tinstalled' "$modules_package" "$version")
expected_image=$(printf '%s\t%s\tarm64\tinstalled' "$image_package" "$version")
grep -Fx "$expected_modules" /linux-work/kernel-package-status >/dev/null
grep -Fx "$expected_image" /linux-work/kernel-package-status >/dev/null
if [ -n "$support_archive" ]; then
	chroot "$root" dpkg-query --show --showformat='${Package}\t${Version}\t${Architecture}\t${db:Status-Status}\n' \
		"$support_package" > /linux-work/boot-support-package-status
	expected_support=$(printf '%s\t%s\tall\tinstalled' "$support_package" "$version")
	grep -Fx "$expected_support" /linux-work/boot-support-package-status >/dev/null
fi

restore_statoverride
rm -rf -- "$backup"
trap - EXIT HUP INT TERM
`
	if err := docker.RunInWorkspaceVolume(ctx, image, workspace, volume,
		"bash", "-ceu", script, "lexr-install-kernel", bundle.ABI, bundle.Version,
		"/work/kernel/"+modulesPackage.Name, "/work/kernel/"+imagePackage.Name, supportArchive); err != nil {
		return fmt.Errorf("register custom kernel packages in remastered root: %w", err)
	}
	return nil
}

// errorsForMissingKernelRole returns a consistent error for an incomplete
// kernel bundle passed to the installed-system hand-off.
func errorsForMissingKernelRole(role kernel.PackageRole) error {
	return fmt.Errorf("kernel bundle has no %s package", role)
}

// installInstalledSystemSupport retains Surface command-line defaults, invokes
// the package-owned helper for the selected external profile, and creates the
// non-Casper initramfs from the extracted root. Concrete GRUB generation is
// deferred until Ubuntu's installer has mounted a real destination filesystem.
func installInstalledSystemSupport(ctx context.Context, docker *platform.Docker, image, workspace, volume string, bundle kernel.Bundle) error {
	profile, _, err := requiredExternalProfile(bundle)
	if err != nil {
		return err
	}
	const script = `set -o pipefail
root=/linux-work/rootfs
abi=$1
delivery=$2
shift 2
support=/work/installed-support

install -d -m 0755 "$root/etc/default/grub.d"
install -m 0644 "$support/99-surface-pro-11.cfg" "$root/etc/default/grub.d/99-surface-pro-11.cfg"

# Fresh images must not carry the retired adapter-generated lifecycle beside
# the generic package-owned implementation.
rm -f -- \
	"$root/etc/grub.d/09_lexr_sp11" \
	"$root/etc/kernel/postinst.d/05-lexr-sp11-dtb" \
	"$root/etc/kernel/postrm.d/05-lexr-sp11-dtb" \
	"$root/usr/local/sbin/lexr-refresh-sp11-boot" \
	"$root/usr/lib/lexr/sp11/kernel-abi" \
	"$root/usr/lib/lexr/sp11/dtb/x1e80100-microsoft-denali-oled.dtb" \
	"$root/usr/lib/lexr/sp11/dtb/x1p64100-microsoft-denali.dtb"
rmdir -- "$root/usr/lib/lexr/sp11/dtb" "$root/usr/lib/lexr/sp11" 2>/dev/null || true

case "$delivery" in
	external-required)
		[ -x "$root/usr/libexec/lexr/kernel-boot-refresh" ] || {
			echo "external-required image has no package-owned boot refresh helper" >&2
			exit 66
		}
		[ "$#" -gt 0 ] || {
			echo "external-required image has no declared platform profile" >&2
			exit 66
		}
		for profile in "$@"; do
			chroot "$root" /usr/libexec/lexr/kernel-boot-refresh refresh \
				--root / --abi "$abi" --image "/boot/vmlinuz-$abi" \
				--platform "$profile" --defer-grub
		done
		;;
	embedded)
		[ "$#" -eq 0 ] || {
			echo "embedded image unexpectedly received external platform profiles" >&2
			exit 65
		}
		[ ! -e "$root/usr/libexec/lexr/kernel-boot-refresh" ] || {
			echo "embedded image unexpectedly contains external boot support" >&2
			exit 65
		}
		;;
	*)
		echo "unsupported effective DTB delivery $delivery" >&2
		exit 65
		;;
esac

test -x /usr/bin/dracut
test -x /usr/lib/dracut/dracut-install
test -d "$root/boot"
test ! -L "$root/boot"
test -x "$root/etc/grub.d/10_linux"
test ! -L "$root/etc/grub.d/10_linux"
test -f "$root/etc/grub.d/10_linux"
generator_size=$(stat -c %s "$root/etc/grub.d/10_linux")
test "$generator_size" -gt 0
test "$generator_size" -le 262144
generator_mode=$(stat -c %a "$root/etc/grub.d/10_linux")
(( (8#$generator_mode & 8#022) == 0 ))
sh -n "$root/etc/grub.d/10_linux"

# The tools image owns the trusted Dracut engine, modules, userspace and
# configuration.  Only the exact package-owned kernel modules and firmware are
# collected from the extracted root.  Dracut's --sysroot cannot express this
# split: it also redirects tooling-owned module scripts through that root.
module_directory="$root/usr/lib/modules/$abi"
firmware_directory="$root/usr/lib/firmware"
tool_firmware_directory=/usr/lib/firmware
test -d "$module_directory"
test ! -L "$module_directory"
test -f "$module_directory/modules.dep"
test ! -L "$module_directory/modules.dep"
test -s "$module_directory/modules.dep"
test -d "$firmware_directory"
test ! -L "$firmware_directory"
install -d -m 0755 "$tool_firmware_directory"
test ! -L "$tool_firmware_directory"
# Preserve canonical /usr/lib/firmware archive paths while keeping the source
# firmware data-only. The disposable tools container is destroyed afterwards.
cp -a -- "$firmware_directory/." "$tool_firmware_directory/"
temporary=$(mktemp "$root/boot/.initrd.img-$abi.lexr.XXXXXX")
contents=$(mktemp "$root/boot/.initrd.img-$abi.contents.lexr.XXXXXX")
long_contents=$(mktemp "$root/boot/.initrd.img-$abi.long-contents.lexr.XXXXXX")
configuration=$(mktemp -d /tmp/lexr-dracut-conf.XXXXXX)
dracut_log=$(mktemp /tmp/lexr-dracut.XXXXXX.log)
cleanup() {
	rm -f -- "$temporary" "$contents" "$long_contents" "$dracut_log"
	rmdir -- "$configuration" 2>/dev/null || true
}
trap cleanup EXIT HUP INT TERM

if ! DRACUT_INSTALL=/usr/lib/dracut/dracut-install \
	dracutbasedir=/usr/lib/dracut \
	/usr/bin/dracut \
		--kmoddir "$module_directory" \
		--fwdir "$tool_firmware_directory" \
		--install "$tool_firmware_directory/ath12k/WCN7850/hw2.0/board.bin" \
		--conf /dev/null \
		--confdir "$configuration" \
		--no-hostonly \
		--no-hostonly-cmdline \
		--no-hostonly-default-device \
		--reproducible \
		--force \
		"$temporary" "$abi" 2>&1 | tee "$dracut_log" >&2
then
	echo "Dracut failed to generate the installed initramfs" >&2
	exit 65
fi
if grep -qF "dracut[E]:" "$dracut_log" || grep -qF "dracut-install: ERROR:" "$dracut_log"; then
	echo "Dracut reported an incomplete installed initramfs" >&2
	exit 65
fi
test -s "$temporary"
lsinitramfs "$temporary" > "$contents"
lsinitramfs -l "$temporary" > "$long_contents"
require_member() {
	member=$1
	grep -qxF "$member" "$contents" || {
		echo "installed initramfs is missing required member $member" >&2
		exit 65
	}
}
require_any_member() {
	label=$1
	shift
	for member in "$@"; do
		if grep -qxF "$member" "$contents"; then
			return 0
		fi
	done
	echo "installed initramfs is missing required capability $label" >&2
	exit 65
}
require_member init
require_member "usr/lib/firmware/ath12k/WCN7850/hw2.0/board.bin"
require_member "usr/lib/modules/$abi/modules.dep"
require_any_member shell usr/bin/sh bin/sh usr/bin/bash bin/bash
require_any_member mount usr/bin/mount bin/mount
require_any_member modprobe usr/sbin/modprobe sbin/modprobe
require_any_member dracut-library usr/lib/dracut-lib.sh lib/dracut-lib.sh
require_any_member root-parser usr/lib/dracut/hooks/cmdline/00-parse-root.sh lib/dracut/hooks/cmdline/00-parse-root.sh
if ! awk -v prefix="usr/lib/modules/$abi/kernel/" '
	$1 ~ /^-/ && index($NF, prefix) == 1 && $NF ~ /\.ko(\.(gz|xz|zst))?$/ { found=1 }
	END { exit(found ? 0 : 1) }
' "$long_contents"; then
	echo "installed initramfs contains no kernel modules for $abi" >&2
	exit 65
fi
if grep -qF "scripts/casper" "$contents"; then
	echo "installed initramfs unexpectedly contains Casper support" >&2
	exit 65
fi
chmod 0644 "$temporary"
mv -f -- "$temporary" "$root/boot/initrd.img-$abi"
rm -f -- "$contents" "$long_contents" "$dracut_log"
rmdir -- "$configuration"
trap - EXIT HUP INT TERM
`
	arguments := []string{
		"bash", "-ceu", script, "lexr-installed-support", bundle.ABI, string(bundle.EffectiveDTBDelivery),
	}
	if profile != "" {
		arguments = append(arguments, profile)
	}
	if err := docker.RunInWorkspaceVolume(ctx, image, workspace, volume, arguments...); err != nil {
		return fmt.Errorf("install exact-ABI kernel, DTB, GRUB, and initramfs support: %w", err)
	}
	return nil
}

// installedGrubDefaults returns the installed operating system's Surface
// command line without Casper options or DSP blacklists.
func installedGrubDefaults() string {
	return `# Surface Pro 11 platform arguments for installed kernels.
GRUB_CMDLINE_LINUX_DEFAULT="${GRUB_CMDLINE_LINUX_DEFAULT} clk_ignore_unused pd_ignore_unused arm64.nopauth systemd.tpm2_wait=0"
GRUB_TIMEOUT_STYLE=menu
GRUB_TIMEOUT=15
`
}

// requiredExternalProfile returns the one package-registry profile selected
// for a raw image. A multi-profile installed image must use embedded delivery.
func requiredExternalProfile(bundle kernel.Bundle) (string, kernel.DeviceTree, error) {
	if bundle.EffectiveDTBDelivery == kernel.DTBDeliveryEmbedded {
		return "", kernel.DeviceTree{}, nil
	}
	if bundle.EffectiveDTBDelivery != kernel.DTBDeliveryExternalRequired {
		return "", kernel.DeviceTree{}, fmt.Errorf("unsupported effective DTB delivery %q", bundle.EffectiveDTBDelivery)
	}
	var selected kernel.DeviceTree
	count := 0
	for _, tree := range bundle.DeviceTrees {
		if tree.Required {
			selected = tree
			count++
		}
	}
	if count != 1 {
		return "", kernel.DeviceTree{}, fmt.Errorf("external-required installed image requires exactly one platform profile; found %d (use embedded delivery for multi-profile media)", count)
	}
	return selected.Device, selected, nil
}

// installedPackageExpectation is one exact dpkg record required in the
// deployable root.
type installedPackageExpectation struct {
	name         string
	version      string
	architecture string
}

// installedPackageExpectations returns the package database records required
// by this bundle's effective delivery contract.
func installedPackageExpectations(bundle kernel.Bundle) []installedPackageExpectation {
	expected := []installedPackageExpectation{
		{name: "linux-modules-" + bundle.ABI, version: bundle.Version, architecture: "arm64"},
		{name: "linux-image-" + bundle.ABI, version: bundle.Version, architecture: "arm64"},
	}
	if bundle.EffectiveDTBDelivery == kernel.DTBDeliveryExternalRequired {
		expected = append(expected, installedPackageExpectation{
			name: "lexr-kernel-boot-support", version: bundle.Version, architecture: "all",
		})
	}
	return expected
}

// installedSupportPaths returns the bundle-bound live-root paths which
// validation extracts before assessing the installed-system hand-off.
func installedSupportPaths(bundle kernel.Bundle) ([]string, error) {
	paths := []string{
		"boot/vmlinuz-" + bundle.ABI,
		"boot/initrd.img-" + bundle.ABI,
		"etc/grub.d/10_linux",
		"etc/default/grub.d/" + installedGrubDefaultsName,
		"var/lib/dpkg/status",
	}
	for _, expected := range installedPackageExpectations(bundle) {
		paths = append(paths, "var/lib/dpkg/info/"+expected.name+".list")
	}
	if bundle.EffectiveDTBDelivery == kernel.DTBDeliveryEmbedded {
		return paths, nil
	}
	profile, tree, err := requiredExternalProfile(bundle)
	if err != nil {
		return nil, err
	}
	paths = append(paths, genericInstalledSupportPaths...)
	relative, ok := tree.FirmwareRelativePath(bundle.ABI)
	if !ok {
		return nil, fmt.Errorf("device tree %s is outside the exact-ABI firmware directory", tree.Device)
	}
	paths = append(paths, "boot/dtbs/"+bundle.ABI+"/"+relative, "boot/dtb-"+bundle.ABI)
	for _, name := range []string{"title", "dtb-path", "dtb-sha256", "machine-identities", "compatibles"} {
		paths = append(paths,
			"usr/lib/lexr/kernel-platforms/"+profile+"/"+name,
			"var/lib/lexr/kernel-boot/"+bundle.ABI+"/"+profile+"/"+name,
		)
	}
	return paths, nil
}

// validateInstalledGRUBGenerator proves a bounded stock 10_linux generator
// prefers the ABI-specific DTB and emits that selected path. A concrete
// grub.cfg cannot be generated safely until Ubuntu's installer has mounted the
// destination disk and grub-probe can identify it.
func validateInstalledGRUBGenerator(path string) error {
	info, err := os.Lstat(path)
	if err != nil {
		return fmt.Errorf("inspect installed GRUB generator: %w", err)
	}
	if !info.Mode().IsRegular() || info.Mode()&0o111 == 0 {
		return fmt.Errorf("installed GRUB generator must be an executable non-symlink regular file")
	}
	if info.Mode().Perm()&0o022 != 0 {
		return fmt.Errorf("installed GRUB generator must not be group- or world-writable")
	}
	if info.Size() == 0 || info.Size() > maximumInstalledGRUBGeneratorBytes {
		return fmt.Errorf("installed GRUB generator size %d is outside 1..%d bytes", info.Size(), maximumInstalledGRUBGeneratorBytes)
	}
	file, err := os.Open(path)
	if err != nil {
		return fmt.Errorf("open installed GRUB generator: %w", err)
	}
	defer file.Close()
	openedInfo, err := file.Stat()
	if err != nil {
		return fmt.Errorf("inspect opened GRUB generator: %w", err)
	}
	if !openedInfo.Mode().IsRegular() || openedInfo.Mode().Perm()&0o022 != 0 || !os.SameFile(info, openedInfo) {
		return fmt.Errorf("installed GRUB generator changed during inspection")
	}
	contents, err := io.ReadAll(io.LimitReader(file, maximumInstalledGRUBGeneratorBytes+1))
	if err != nil {
		return fmt.Errorf("read installed GRUB generator: %w", err)
	}
	if int64(len(contents)) > maximumInstalledGRUBGeneratorBytes {
		return fmt.Errorf("installed GRUB generator exceeds %d bytes", maximumInstalledGRUBGeneratorBytes)
	}

	lines := make([]string, 0)
	for _, line := range strings.Split(strings.ReplaceAll(string(contents), "\r\n", "\n"), "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}
		lines = append(lines, strings.Join(strings.Fields(trimmed), " "))
	}
	emission := `devicetree ${rel_dirname}/${dtb}`
	emissionIndex := -1
	for index, line := range lines {
		if line == emission {
			if emissionIndex != -1 {
				return fmt.Errorf("installed GRUB generator repeats its exact device-tree emission")
			}
			emissionIndex = index
		} else if fields := strings.Fields(line); len(fields) > 0 && fields[0] == "devicetree" {
			return fmt.Errorf("installed GRUB generator has a conflicting device-tree emission")
		}
	}
	if emissionIndex == -1 {
		return fmt.Errorf("installed GRUB generator lacks its exact device-tree emission")
	}
	uniqueLine := func(wanted string) (int, error) {
		position := -1
		for index, line := range lines {
			if line != wanted {
				continue
			}
			if position != -1 {
				return -1, fmt.Errorf("installed GRUB generator repeats %q", wanted)
			}
			position = index
		}
		if position == -1 {
			return -1, fmt.Errorf("installed GRUB generator lacks %q", wanted)
		}
		return position, nil
	}
	functionIndex, err := uniqueLine("linux_entry ()")
	if err != nil {
		return err
	}
	parameterIndex, err := uniqueLine(`version="$2"`)
	if err != nil {
		return err
	}
	guardIndex, err := uniqueLine(`if test -n "${dtb}" ; then`)
	if err != nil {
		return err
	}
	if !(functionIndex < parameterIndex && parameterIndex < guardIndex && guardIndex < emissionIndex) {
		return fmt.Errorf("installed GRUB generator does not keep its guarded device-tree emission inside linux_entry")
	}

	derivation := []string{
		`for linux in ${reverse_sorted_list}; do`,
		"basename=`basename $linux`",
		"dirname=`dirname $linux`",
		"rel_dirname=`make_system_path_relative_to_its_root $dirname`",
		`version=` + "`" + `echo $basename | sed -e "s,^[^0-9]*-,,g"` + "`",
		`alt_version=` + "`" + `echo $version | sed -e "s,\.old$,,g"` + "`",
	}
	derivationPositions := make([]int, len(derivation))
	for wantedIndex, value := range derivation {
		derivationPositions[wantedIndex] = -1
		for lineIndex, line := range lines {
			if line == value {
				if derivationPositions[wantedIndex] != -1 {
					return fmt.Errorf("installed GRUB generator repeats kernel version derivation %q", value)
				}
				derivationPositions[wantedIndex] = lineIndex
			}
		}
		if derivationPositions[wantedIndex] == -1 {
			return fmt.Errorf("installed GRUB generator lacks kernel version derivation %q", value)
		}
		if wantedIndex > 0 && derivationPositions[wantedIndex] <= derivationPositions[wantedIndex-1] {
			return fmt.Errorf("installed GRUB generator orders %q before its required predecessor", value)
		}
	}

	header := `for i in "dtb-${version}" "dtb-${alt_version}" "dtb"; do`
	body := []string{
		`if test -e "${dirname}/${i}" ; then`, `dtb="$i"`, `break`, `fi`, `done`,
	}
	headerIndex := -1
	for index, line := range lines {
		if line == header {
			if headerIndex != -1 {
				return fmt.Errorf("installed GRUB generator repeats the exact-ABI device-tree lookup")
			}
			headerIndex = index
		}
	}
	if headerIndex < 1 || lines[headerIndex-1] != "dtb=" {
		return fmt.Errorf("installed GRUB generator lacks canonical device-tree initialisation and exact-ABI lookup")
	}
	if headerIndex <= derivationPositions[len(derivationPositions)-1] {
		return fmt.Errorf("installed GRUB generator selects a device tree before deriving the kernel version")
	}
	for offset, expected := range body {
		index := headerIndex + offset + 1
		if index >= len(lines) || lines[index] != expected {
			return fmt.Errorf("installed GRUB generator lacks canonical lookup step %q", expected)
		}
	}
	for index, line := range lines {
		if index != headerIndex-1 && index != headerIndex+2 &&
			(strings.HasPrefix(line, "dtb=") || line == "unset dtb") {
			return fmt.Errorf("installed GRUB generator changes the selected device tree outside the canonical lookup")
		}
		if strings.HasPrefix(line, "basename=") && index != derivationPositions[1] {
			return fmt.Errorf("installed GRUB generator changes the kernel basename outside the canonical derivation")
		}
		if strings.HasPrefix(line, "version=") && line != `version="$2"` && index != derivationPositions[4] {
			return fmt.Errorf("installed GRUB generator changes the kernel version outside the canonical derivation")
		}
	}
	if emissionIndex >= derivationPositions[0] {
		return fmt.Errorf("installed GRUB generator's device-tree template is outside linux_entry")
	}
	for _, line := range lines[derivationPositions[len(derivationPositions)-1]+1 : headerIndex] {
		if line == "exit" || strings.HasPrefix(line, "exit ") {
			return fmt.Errorf("installed GRUB generator exits before selecting the per-kernel device tree")
		}
	}
	called := false
	for _, line := range lines[headerIndex+len(body)+1:] {
		if strings.HasPrefix(line, `linux_entry "${OS}" "${version}" `) {
			called = true
			break
		}
	}
	if !called {
		return fmt.Errorf("installed GRUB generator never calls linux_entry after selecting the per-kernel device tree")
	}
	return nil
}

// installedPackageStatus reports whether one exact package stanza is marked as
// installed with the expected version and architecture.
func installedPackageStatus(status, packageName, version, architecture string) bool {
	for _, paragraph := range strings.Split(strings.ReplaceAll(status, "\r\n", "\n"), "\n\n") {
		fields := make(map[string]string)
		for _, line := range strings.Split(paragraph, "\n") {
			key, value, ok := strings.Cut(line, ":")
			if ok {
				fields[key] = strings.TrimSpace(value)
			}
		}
		if fields["Package"] == packageName && fields["Version"] == version &&
			fields["Architecture"] == architecture && fields["Status"] == "install ok installed" {
			return true
		}
	}
	return false
}

// installedPackagePresent reports whether any status paragraph declares the
// exact package name, regardless of configuration state.
func installedPackagePresent(status, packageName string) bool {
	for _, paragraph := range strings.Split(strings.ReplaceAll(status, "\r\n", "\n"), "\n\n") {
		for _, line := range strings.Split(paragraph, "\n") {
			if line == "Package: "+packageName {
				return true
			}
		}
	}
	return false
}

// squashFSListingContainsPath matches one exact member in unsquashfs -ll
// output without accepting a basename prefix or suffix.
func squashFSListingContainsPath(listing, wanted string) bool {
	wanted = strings.TrimPrefix(filepath.ToSlash(wanted), "/")
	for _, line := range strings.Split(listing, "\n") {
		fields := strings.Fields(line)
		if len(fields) == 0 {
			continue
		}
		candidate := strings.TrimPrefix(filepath.ToSlash(fields[len(fields)-1]), "squashfs-root/")
		if candidate == wanted {
			return true
		}
	}
	return false
}
